FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:run

RUN install_packages libomxil-bellagio-bin libxcb1 libxcb-shm0 ffmpeg locales-all
COPY entry.sh /entry.sh
RUN chmod +x /entry.sh

ENTRYPOINT /entry.sh 2h

